[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/assessment"
  to = "/assessment.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200